#!/usr/bin/env bash
require() {
  hash "$@" || exit
}
require find parallel colorguard nproc
RED="\e[31m"
ENDCOLOR="\e[0m"
declare -i PROCS=$(($(nproc) - 1))
files=$(find . -type f -name "*.css"! -name "*.scss.css" ! -name "*.sass.css" \
  ! -path "**/.git/**" ! -path "*/node_modules/*")
echo -e "${RED}Executing colorguard...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    colorguard --file % --allow-equivalent-notation
