#!/usr/bin/env bash
#shellcheck disable=SC1091
source ./require.sh
source ./errorhandlers.sh
source ./colors.sh
require find parallel colorguard nproc
declare -i PROCS=$(($(nproc) - 1))
files=$(find . -type f -name "*.css"! -name "*.scss.css" ! -name "*.sass.css" \
  ! -path "**/.git/**" ! -path "*/node_modules/*")
echo -e "${GREEN}Executing colorguard...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    colorguard --file % --allow-equivalent-notation
