#!/usr/bin/env bash
require() {
  hash "$@" || exit
}
require csslint htmlhint stylelint prettier tidy find parallel head
declare -i SUCCESS=0
declare -i CSS_SUCCESS=0
declare -r configFileName="tidy.config"
configFilePath="$(find . -maxdepth 2 \
  -type f -name "$configFileName" ! -path \
  "**/.git/**" | head -n 1)"
files=$(find . -type f -name "*.css" \
  ! -path "**/.git/**")
echo "Executing csslint..."
echo "$files" |
  parallel -j 5 -I% \
    csslint --quiet --format=compact %
CSS_SUCCESS=$?
echo "Executing stylelint..."
echo "$files" |
  parallel -j 5 -I% \
    stylelint % --fix
STYLE_SUCCESS=$CSS_SUCCESS+$?
if [[ $STYLE_SUCCESS == 0 ]]; then
  echo "Executing prettier..."
  echo "$files" |
    parallel -j 5 -I% \
      prettier --parser css --write %
  STYLE_SUCCESS=$STYLE_SUCCESS+$?
fi
files=$(find . -maxdepth 2 -type f -name "*.html" \
  ! -path "**/.git/**")
echo "Executing htmlhint..."
echo "$files" |
  parallel -j 5 -I% \
    htmlhint --config .htmlhintrc -f compact %
SUCCESS=$?
if [[ $SUCCESS == 0 ]]; then
  echo "Executing tidy..."
  echo "$files" |
    parallel -j 5 -I% \
      tidy -config "$configFilePath" -quiet -m %
  SUCCESS=$SUCCESS+$?
fi
exit "$((SUCCESS + STYLE_SUCCESS))"
