#!/usr/bin/env bash
require() {
  hash "$@" || exit
}
require htmlhint stylelint prettier tidy find parallel colorguard html-validate js-beautify nproc
RED="\e[31m"
ENDCOLOR="\e[0m"
declare -i SUCCESS=0
declare -i STYLE_SUCCESS=0
declare -r configFileName="tidy.config"
declare -i PROCS=$(($(nproc) - 1))
files=$(find . -type f -name "*.css" ! -name "*.scss.css" ! -name "*.sass.css" \
  ! -path "**/.git/**" ! -path "**/node_modules/**")
echo -e "${RED}Executing colorguard...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    colorguard --file % --allow-equivalent-notation
STYLE_SUCCESS=$((STYLE_SUCCESS + $?))
echo -e "${RED}Executing prettier for css...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    prettier --cache --parser css --write %
STYLE_SUCCESS=$((STYLE_SUCCESS + $?))
files=$(find . -type f -name "*.css" ! -name "*.scss.css" ! -name "*.sass.css" ! -name "tw-*.css" \
  ! -path "**/.git/**" ! -path "**/node_modules/**")
echo -e "${RED}Executing stylelint for css...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    stylelint % --color --fix --quiet-deprecation-warnings
STYLE_SUCCESS=$((STYLE_SUCCESS + $?))
files=$(find . -type f -name "*.scss" \
  ! -path "**/.git/**" ! -path "**/node_modules/**" ! -path "**/*tailwind.css")
echo -e "${RED}Executing prettier for scss...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    prettier --cache --parser scss --write %
STYLE_SUCCESS=$((STYLE_SUCCESS + $?))
echo -e "${RED}Executing stylelint for scss...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    stylelint % --color --fix --quiet-deprecation-warnings
STYLE_SUCCESS=$((STYLE_SUCCESS + $?))
files=$(find . -maxdepth 2 -type f -name "*.html" \
  ! -path "**/.git/**")
echo -e "${RED}Executing tidy...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    tidy -config "$configFileName" -quiet -m %
SUCCESS=$((SUCCESS + $?))
echo -e "${RED}Executing prettier for html...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    prettier --cache --parser html --write %
SUCCESS=$((SUCCESS + $?))
echo -e "${RED}Executing htmlhint...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    htmlhint --config .htmlhintrc -f compact % 2>/dev/null
SUCCESS=$?
echo -e "${RED}Executing html-validate...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    html-validate --formatter stylish %
SUCCESS=$((SUCCESS + $?))
files=$(find . -type f -name "*.js" \
  ! -path "**/.git/**" ! -path "**/node_modules/**" ! -path "**/*tailwind.css")
echo -e "${RED}Executing js-beautify for js...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    js-beautify -r %
SUCCESS=$((SUCCESS + $?))
files=$(find . -type f -name "*.scss" ! -name "_*.scss" \
  ! -path "**/.git/**" ! -path "**/node_modules/**" ! -path "**/*tailwind.css")
echo -e "${RED}Executing sass for scss...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I@ \
    ./runsass @
SUCCESS=$((SUCCESS + $?))
files=$(find . -type f -name "*.sass" \
  ! -path "**/.git/**" ! -path "**/node_modules/**" ! -path "**/*tailwind.css")
echo -e "${RED}Executing sass for sass...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    ./runsass %
SUCCESS=$((SUCCESS + $?))
echo -e "${RED}Executing prettier for svg...${ENDCOLOR}"
prettier --cache --parser html --write -- **/*.svg
SUCCESS=$((SUCCESS + $?))
exit $((SUCCESS + STYLE_SUCCESS))
