#!/usr/bin/env bash
#shellcheck disable=SC1091
source ./require.sh
source ./colors.sh
source ./errorhandlers.sh
require sass
filenames=("$@")
declare -i exitCode=0
for fname in "${filenames[@]}"; do
  sass --quiet --no-source-map --update "$fname" "${fname}.css"
  exitCode=$((exitCode + $?))
done
exit "$exitCode"
