#!/usr/bin/env bash
#shellcheck disable=SC1091
source ./require.sh
source ./errorhandlers.sh
source ./colors.sh
require find parallel nproc
declare -i PROCS=$(($(nproc) - 1))
files=$(find . -type f -name "*.scss" ! -name "_*.scss" \
  ! -path "**/.git/**" ! -path "**/node_modules/**" ! -path "**/*tailwind.css")
echo -e "${GREEN}Executing sass for scss...${ENDCOLOR}"
echo "$files" |
  parallel -X --bar -j "$PROCS" -I@ \
    ./runsass @
SUCCESS=$?
files=$(find . -type f -name "*.sass" \
  ! -path "**/.git/**" ! -path "**/node_modules/**" ! -path "**/*tailwind.css")
echo -e "${GREEN}Executing sass for sass...${ENDCOLOR}"
echo "$files" |
  parallel -X --bar -j "$PROCS" -I% \
    ./runsass %
exit $((SUCCESS + $?))
