#!/usr/bin/env bash
#shellcheck disable=SC1091
source ./require.sh
source ./errorhandlers.sh
source ./colors.sh
require stylelint find parallel nproc
declare -i PROCS=$(($(nproc) - 1))
files=$(find . -type f -name "*.css" ! -name "*.scss.css" ! -name "*.sass.css" ! -name "tw-*.css" \
  ! -path "**/.git/**" ! -path "**/node_modules/**")
echo -e "${GREEN}Executing stylelint for css...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    stylelint % --fix --quiet-deprecation-warnings
exit $?
