#!/usr/bin/env bash
require() {
  hash "$@" || exit
}
require stylelint find parallel nproc
RED="\e[31m"
ENDCOLOR="\e[0m"
declare -i PROCS=$(($(nproc) - 1))
files=$(find . -type f -name "*.css" ! -name "*.scss.css" ! -name "*.sass.css" \
  ! -path "**/.git/**" ! -path "**/node_modules/**" ! -path "**/*tailwind.css")
echo -e "${RED}Executing stylelint for css...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    stylelint % --fix --quiet-deprecation-warnings
 exit $?   

