#!/usr/bin/env bash
#shellcheck disable=SC1091
source ./require.sh
source ./errorhandlers.sh
source ./colors.sh
require prettier find parallel nproc
declare -i PROCS=$(($(nproc) - 1))
files=$(find . -type f -name "*.css" ! -name "*.scss.css" ! -name "*.sass.css" \
  ! -path "**/.git/**" ! -path "**/node_modules/**")
echo -e "${GREEN}Executing prettier for css...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    prettier --cache --parser css --write %
STYLE_SUCCESS=$?
files=$(find . -type f -name "*.scss" \
  ! -path "**/.git/**" ! -path "**/node_modules/**" ! -path "**/*tailwind.css")
echo -e "${GREEN}Executing prettier for scss...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    prettier --cache --parser scss --write %
exit $((STYLE_SUCCESS + $?))
