#!/usr/bin/env bash
#shellcheck disable=SC1091
source ./require.sh
source ./errorhandlers.sh
source ./colors.sh
require find parallel js-beautify nproc
declare -i PROCS=$(($(nproc) - 1))
files=$(find . -type f -name "*.js" \
  ! -path "**/.git/**" ! -path "**/node_modules/**" ! -path "**/*tailwind.css")
echo -e "${GREEN}Executing js-beautify for js...${ENDCOLOR}"
echo "$files" |
  parallel -j "$PROCS" -I% \
    js-beautify -r %
exit $?
