#!/usr/bin/env bash
#shellcheck disable=SC1091
source ./require.sh
source ./errorhandlers.sh
source ./colors.sh
require prettier find parallel
GREEN="\e[31m"
ENDCOLOR="\e[0m"
echo -e "${GREEN}Executing prettier for svg...${ENDCOLOR}"
prettier --cache --parser html --write -- **/*.svg
exit $?
