#!/usr/bin/env bash
#shellcheck disable=SC1091
source ./require.sh
source ./errorhandlers.sh
source ./colors.sh
require prettier find parallel
echo -e "${GREEN}Executing prettier for svg...${ENDCOLOR}"
prettier --log-level silent --cache --parser html --write -- **/*.svg
exit $?
