#!/usr/bin/env bash
require() {
  hash "$@" || exit
}
require prettier find parallel
RED="\e[31m"
ENDCOLOR="\e[0m"
echo -e "${RED}Executing prettier for svg...${ENDCOLOR}"
prettier --cache --parser html --write -- **/*.svg
exit $?
