#!/usr/bin/env bash
#shellcheck disable=SC1091
source ./require.sh
source ./errorhandlers.sh
source ./colors.sh
require prettier tidy find parallel nproc
declare -r configFileName="tidy.config"
declare -i PROCS=$(($(nproc) - 1))
files=$(find . -maxdepth 2 -type f -name "*.html" \
  ! -path "**/.git/**")
echo -e "${GREEN}Executing tidy...${ENDCOLOR}"
echo "$files" |
  parallel --bar -j "$PROCS" -I% \
    ./wraptidy -config "$configFileName" -quiet -m %
SUCCESS=$?
echo -e "${GREEN}Executing prettier for html...${ENDCOLOR}"
echo "$files" |
  parallel --bar -j "$PROCS" -I% \
    prettier --log-level silent --cache --parser html --write %
exit $((SUCCESS + $?))
